source "https://rubygems.org"

ruby "3.3.4"

# [1] Back-End
gem "rails", "~> 7.1.3", ">= 7.1.3.4"
# [1.1] APIs
# JSON APIs
gem "jbuilder"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"


# [2] Storage
gem "pg", "~> 1.1"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"


# [4] Deployment
# App server
gem "puma", ">= 5.0"


# [5] Config
# Caching: Reduces boot time
gem "bootsnap", require: false


# [6] Tools - Windows
# Time Zone info
gem "tzinfo-data", platforms: %i[ windows jruby ]


group :development, :test do
  # [6] Tools
  # Debug
  gem "debug", platforms: %i[ mri windows ]
  gem "faker", "~> 3.4"

  ## Fixture - Models
  gem "factory_bot_rails", "~> 6.4"
  ## Fixture - Fake data
  gem "pry-rails", "~> 0.3.11"

  # [7] Testing
  gem "rspec-rails", "~> 6.1"
  # Auto-run on Modifications
  gem "guard", "~> 2.18"
  gem "guard-rspec", "~> 4.7"

end

group :test do
  # [6] Tools
  # Matchers/Helpers for shorten and simple tests
  gem "shoulda-matchers", "~> 6.2"
  # Strategies for cleaning databases
  gem "database_cleaner", "~> 2.0"
  gem "database_cleaner-active_record", "~> 2.2"
  # Test Coverage
  gem "simplecov", "~> 0.22.0", require: false
end

group :development do
  # [6] Tools
  # Pre-load app for console, rake and tests.
  # gem "spring"
  # Errors
  gem "better_errors", "~> 2.10"
  # Models
  gem "annotate", "~> 3.2"
end
