source "https://rubygems.org"

ruby "3.3.4"

# [1] Back-End
gem "rails", "~> 7.1.3", ">= 7.1.3.4"
# [1.1] APIs
# JSON APIs
# gem "jbuilder"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"


# [2] Storage
gem "pg", "~> 1.1"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"


# [4] Deployment
# App server
gem "puma", ">= 5.0"


# [5] Config
# Caching: Reduces boot time
gem "bootsnap", require: false


# [6] Tools - Windows
# Time Zone info
gem "tzinfo-data", platforms: %i[ windows jruby ]


group :development, :test do
  # [6] Tools
  # Debug
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  # [6] Tools
  # Pre-load app for console, rake and tests.
  # gem "spring"
end

