services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring_sys_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rails:
    build:
      context: .
      dockerfile: ./rails-container/Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: monitoring_sys_development
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3030:3030"
    depends_on:
      - postgres

  vue:
    build:
      context: .
      dockerfile: ./vue-container/Dockerfile
    volumes:
      - ..:/workspace:cached
    # command: sh -c "yarn install && yarn serve"
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - rails

  playwright:
    image: mcr.microsoft.com/playwright:v1.39.0-jammy  # Use the latest version
    working_dir: /workspace/frontend
    volumes:
      - ..:/workspace:cached
    depends_on:
      - vue
    command: sh -c "yarn install && npx playwright install && tail -f /dev/null"

volumes:
  postgres-data:
