name: monitoring-schedule

services:
  postgres:
    container_name: monit-pg
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring_sys_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-net

  rails:
    container_name: monit-rails
    build:
      context: .
      dockerfile: ./rails-container/Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: monitoring_sys_development
    volumes:
      - ..:/workspace:cached
    networks:
      - frontend-net
      - backend-net
    command: sleep infinity
    ports:
      - "3030:3030"
    depends_on:
      - postgres

  vue:
    container_name: monit-vue
    build:
      context: .
      dockerfile: ./vue-container/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - frontend-net
    # command: sh -c "yarn install && yarn serve"
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - rails

  playwright:
    container_name: monit-playwright
    image: mcr.microsoft.com/playwright:v1.39.0-jammy  # Use the latest version
    working_dir: /workspace/frontend
    user: pwuser
    volumes:
      - ..:/workspace:cached
    networks:
      - frontend-net
    depends_on:
      - vue
    command: sh -c "yarn install && npx playwright install && tail -f /dev/null"

volumes:
  postgres-data:

networks:
  backend-net: {}
  frontend-net: {}